# Generated by Django 3.0.1 on 2019-12-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingTitle', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=500)),
                ('postalCode', models.IntegerField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=500)),
                ('phoneNumber', models.IntegerField(blank=True)),
            ],
        ),
    ]
