# Generated by Django 3.0.1 on 2019-12-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='city',
            field=models.CharField(max_length=500, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='description',
            field=models.TextField(help_text='(please remember to put a price if needed)'),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='phoneNumber',
            field=models.IntegerField(blank=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='postalCode',
            field=models.IntegerField(verbose_name='Postal/Zip Code'),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='postingTitle',
            field=models.CharField(max_length=2000, verbose_name='Title'),
        ),
    ]
